### ISSUE TITLE
User roles and permissions doesn't works

### ISSUE THREAD

**Issue by MouadBH** [nasirkhan/laravel-starter#206]
giving role or permissions to users didnt apply.

https://www.loom.com/share/120edc3a5d8748fb9551e01e4c8374b1

**Comment by nasirkhan** [comment]
Sometime this happens that you changed the role and it does not show up in frontend. But if you check the database you will find that it updated properly. 

The solution of this issue is to clear the cache `php artisan cache:clear`. Sometimes this command may not solve the issue! then you can run the command with `sudo` >  `sudo php artisan cache:clear`.

This happens due to the the package i used here for role-permission. 

Please try the mentioned steps and let me know if it solves the issue.

**Comment by MouadBH** [comment]
Thank you @nasirkhan, It works.
