### ISSUE TITLE
For languages

### ISSUE THREAD

**Issue by stormtr** [nasirkhan/laravel-starter#214]
dear Nasir please add config/App under 'Locale'
    'locales' => [
        'en' => 'English', 
        'tr' => 'Turkish', 
        //'fr' => 'French',
        //'de' => 'Germany',
    ],

and the in Language controller add this 
![image](https://user-images.githubusercontent.com/7202660/89303407-d5d0c200-d674-11ea-8552-c5984a36e339.png)

        $list_lang = config('app.locales');
        //dd($list_lang);

        if(!isset($list_lang[$language]))
        {
            abort('403', 'Language is not in Your Selection Please Check APP');
        }

it will check the language for support other wise if y ou add forexample zz, zzz , zzzz etc..  it will return always

**Comment by nasirkhan** [comment]
thanks for the suggestion. 

There are a number of issues i would like to mention here, 

1. I assume you want to have an array of languages in the config. Rather changing the `locale` to an array we should try some different approach. 
2. If I add an array of supported languages, it can be used in other places, like showing the language dropdown and so on. 
3. Just adding a language will not enable the language, you have to create the language files in right places. otherwise there is no point of adding additional language names. 
4. This project is not so ready for non tech users, so adding some first options may not be helpful. One language is added and if someone wants to add more, they can easily do that. One thing can be done, which is add documentation for that. 

I am not against of adding this but it will impact on other places and need to update several other files as well. So before making any such change we can discuss first.
