### ISSUE TITLE
issue in login with facebook

### ISSUE THREAD

**Issue by nikulvnnovate** [nasirkhan/laravel-starter#218]
Thanks for the great laravel starter kit

I have found one issue when implementing login with facebook. If user facebook account does not have email ID than the laravel shows error:

**Argument 1 passed to Illuminate\Auth\SessionGuard::login() must implement interface Illuminate\Contracts\Auth\Authenticatable, instance of Illuminate\Http\RedirectResponse given, called in /home3/papluwoq/digicard.paplu.tech/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php on line 307**

**Comment by nasirkhan** [comment]
Yes, the Laravel and this starter application will throw an error. The reason is the application uses Email as the primary key in the user table. 

There are multiple ways to solve this issue, as i did not need earlier i did not look into that. But I know without email registration does not work and that is why the Twitter login is not implemented. 

A solution could be showing a form to enter the email address to those who does not have email address (and other fields if necessary) with their account. Then use that to register the user. Or you can simply show an error that the email is not available. 

If you implemented the solution, you may submit a pull request here as well.

**Comment by nikulvnnovate** [comment]
The code is already there to send error message "Email is not available". but its still throwing error

**Comment by nasirkhan** [comment]
As i mentioned earlier registration without email address is not addressed
completely. Though it shows an exception but the the email is the primary
email address key in the users table to the mysql will through an error as
well.

--
*Nasir Khan Saikat*
www.nasirkhn.com
