### ISSUE TITLE
[Laravel 10] Error: Call to a member function diffForHumans()

### ISSUE THREAD

**Issue by ghost** [nasirkhan/laravel-starter#384]
Hello Nasir!

I tried to make the stater package on Laravel 10. For this, I needed to remove:
```
#  Following packages does not work on Framework 10
"alexusmai/laravel-file-manager": "^3.0", 
"mews/purifier": "^3.3",
```
I also needed to upgrade:

```
"require": {
       ...
       "arcanedev/log-viewer": "9.0.0",
       -----> "arcanedev/log-viewer": "^10.0@dev",
       "laravel/sanctum": "^2.14.1",
       -----> "laravel/sanctum": "^3.2",
       "laravel/tinker": "^2.8",
       ...
}
```
as well as
```
    "require-dev": {
        "laravel/sail": "^1.18",
        "laravel/breeze": "^1.18",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.0",
        "spatie/laravel-ignition": "^2.0"
    },
```
Thereafter everything including backend works. There is a small error generating in the frontend. If there is a fast solution for this, I would be able to use Laravel 10. Here is the error:

```
Error
PHP 8.1.14
Laravel 10.0.0
Call to a member function diffForHumans() on string

Modules/Article/Entities/Presenters/PostPresenter.php:28

    public function getPublishedAtFormattedAttribute()
    {
        $diff = Carbon::now()->diffInHours($this->published_at);
        if ($diff < 24) {
            return $this->published_at->diffForHumans();
        } else {
            return $this->published_at->isoFormat('llll');
        }
    }

```

Any hints?
Thanks

NB: This is not on production at the moment. I only need a working installation on Laravel 10 to work on other things.

**Comment by DeRaja** [comment]
In the backend, I see this error in log as follows:

`Call to a member function isoFormat() on string {"view":,"exception":"[object] (Spatie\\LaravelIgnition\\Exceptions\\ViewException(code: 0): Call to a member function isoFormat() on string at /home/wemul/web/v4b.articles.net/public_html/Modules/Article/Entities/Presenters/PostPresenter.php:30) `

**Comment by ghost** [comment]
In the backend, I see this error in log as follows:

`Call to a member function isoFormat() on string {"view":,"exception":"[object] (Spatie\\LaravelIgnition\\Exceptions\\ViewException(code: 0): Call to a member function isoFormat() on string at /public_html/Modules/Article/Entities/Presenters/PostPresenter.php:30) `

**Comment by nasirkhan** [comment]
Thank you for your interest in upgrading to Laravel 10. 

Laravel Starter used a number of packages, and I am not sure if all the packages are compatible with Laravel 10. I am planning to check the new version this week, I will post the updates here as well.

**Comment by DeRaja** [comment]
Hello Nasir!

Thanks for taking time to review this report. Because I would like to work with the starter project and Laravel 10 is already out, I am totally stuck. At the time of reviewing, if you follow what I have done, then you can narrow down that area, where the first crash on Laravel 10 occurs.

After deactivating a couple of packages, as mentioned in my issue opening comment, then I can proceed. If it is possible to give a very quick fix on my issue, that would help.

Thanks in advance.

**Comment by ghost** [comment]
Hello Nasir!

Did you have time to check this issue and see if there is a possibi8lity of a quick fix on L10?

**Comment by DeRaja** [comment]
It is quite unfortunate that I have to see, if I can work without this starter project and find some other solution.

I also see that the dependency of such functions can create a hault of work, if there is a lag of updating.

I would have really wished to wirk with this project but due to lack of support of an update, I have to find alternative solutions.

**Comment by nasirkhan** [comment]
I am very sorry that I could follow your timeline. This is a open source project and I try to contribute as often as possible. But I can not work here bypassing my regular work. 

If you are working on some project and need professional assistance I am help you that separately. Please email me with your proposal.

**Comment by nasirkhan** [comment]
Laravel Starter Upgraded to Laravel 10
